### ISSUE TITLE
When i try to sing in selfhost not singin

### ISSUE THREAD

**Issue by visi91** [ceviixx/umami-Analytics-App#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ceviixx** [comment]
Hi @visi91,
sorry for the delay.

Which version of umami you're using?

**Comment by visi91** [comment]
Hi Clemens , thanks for your reply i have the last version 4.0.0, actually
now everything is
Working fine  is fix i dont now what happning , i just restart my phone ,
was ok

**Comment by ceviixx** [comment]
Hi @visi91, 
Nice to hear that you no can login and view your insights. 


Maybe the could be a better display on the first login. 
I checked it and detected, that if you login, you receive haptic feedback but no loading indicator - I will improve this.

**Comment by ceviixx** [comment]
Added "Subloading" after login.
Will released in v4.0.1
