### ISSUE TITLE
Widget does not show up after updating to version 4.0.0

### ISSUE THREAD

**Issue by weigandf** [ceviixx/umami-Analytics-App#3]
**Describe the bug**
After updating to version 4.0.0 the widgets did disappear and I can not add them to the lock screen anymore

**To Reproduce**
1. Update to version 4.0.0

**Expected behavior**
Widget available 

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone 12pro
 - OS: iOS 18.1

**Additional context**
-

**Comment by ceviixx** [comment]
Hi @weigandf, sorry for the delay. Did you delete the app and installed it new? 

May there is an issue with the 'multiple host' support which kills the widgets on updating.
